name: SpawnerKiller
version: ${project.version}
main: tr.donsuzturk.spawnerkiller.Main
api-version: 1.17
authors: [ DonsuzTurk ]
description: Automatically kills creatures spawner and drops their items.
commands:
  spawnerkiller:
    aliases:
      - spkiller